/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        canvas: '#fdfcfc',
        ink: '#201d1d',
        'ink-deep': '#0f0000',
        charcoal: '#302c2c',
        body: '#424245',
        mute: '#646262',
        stone: '#6e6e73',
        ash: '#9a9898',
        'surface-soft': '#f8f7f7',
        'surface-card': '#f1eeee',
        'surface-dark': '#201d1d',
        'surface-dark-elevated': '#302c2c',
        hairline: 'rgba(15, 0, 0, 0.12)',
        'hairline-strong': '#646262',
        'on-dark': '#fdfcfc',
        'on-dark-mute': '#9a9898',
        'on-primary': '#fdfcfc',
        primary: '#201d1d',
        accent: '#007aff',
        'accent-hover': '#0056b3',
        'accent-active': '#004085',
        warning: '#ff9f0a',
        'warning-hover': '#cc7f08',
        'warning-active': '#995f06',
        danger: '#ff3b30',
        'danger-hover': '#d70015',
        'danger-active': '#a50011',
        success: '#30d158',
      },
      fontFamily: {
        mono: [
          '"Berkeley Mono"',
          '"JetBrains Mono"',
          '"IBM Plex Mono"',
          '"Geist Mono"',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
      spacing: {
        xxs: '1px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '32px',
        section: '96px',
      },
      borderRadius: {
        none: '0px',
        sm: '4px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
